-- 코드를 작성해주세요


SELECT 
YEAR(e.DIFFERENTIATION_DATE) AS YEAR, 
t.max_size - e.SIZE_OF_COLONY AS YEAR_DEV, 
e.ID
FROM ECOLI_DATA e
JOIN (
     SELECT YEAR(DIFFERENTIATION_DATE) AS year,
           MAX(SIZE_OF_COLONY) AS max_size
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) t
ON t.year = YEAR(e.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV